-- CreateTable
CREATE TABLE User (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    password TEXT NOT NULL
);

-- CreateTable
CREATE TABLE Link (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description TEXT NOT NULL,
    url TEXT NOT NULL,
    postedById VARCHAR(255) NOT NULL,
    CONSTRAINT Link_postedById_fkey FOREIGN KEY (postedById) REFERENCES User (id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE Vote (
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    linkId VARCHAR(255) NOT NULL,
    userId VARCHAR(255) NOT NULL,
    CONSTRAINT Vote_linkId_fkey FOREIGN KEY (linkId) REFERENCES Link (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT Vote_userId_fkey FOREIGN KEY (userId) REFERENCES User (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX User_email_key ON User(email);

-- CreateIndex
CREATE UNIQUE INDEX Vote_linkId_userId_key ON Vote(linkId, userId);
